# Generated by Django 2.1.4 on 2018-12-22 22:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appStock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDevolucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateField()),
                ('cantidad_producto', models.PositiveIntegerField(default=0)),
                ('observacion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Ordenes de Devolucion',
            },
        ),
        migrations.CreateModel(
            name='OrdenEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateField()),
                ('cantidad_producto', models.PositiveIntegerField(default=0)),
                ('observacion', models.TextField(blank=True)),
                ('proveedor', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Ordenes de Entrada',
            },
        ),
        migrations.CreateModel(
            name='OrdenSalida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateField()),
                ('cantidad_producto', models.PositiveIntegerField(default=0)),
                ('observacion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('A', 'Activa'), ('C', 'Cerrada'), ('M', 'Modificada')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Ordenes de Salida',
            },
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['fecha_actualizacion'], 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('S', 'Stock'), ('B', 'BackUp'), ('U', 'En USO')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='identificador',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='observacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='ubicacion',
            field=models.CharField(default='Deposito', max_length=200),
        ),
        migrations.AddField(
            model_name='ordensalida',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appStock.Producto'),
        ),
        migrations.AddField(
            model_name='ordenentrada',
            name='producto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='appStock.Producto'),
        ),
        migrations.AddField(
            model_name='ordendevolucion',
            name='orden_salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appStock.OrdenSalida', verbose_name='Orden de Salida'),
        ),
    ]
