# Generated by Django 2.1.4 on 2018-12-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStock', '0005_auto_20181223_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['fecha_entrada'], 'verbose_name_plural': 'Productos'},
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='fecha_actualizacion',
            new_name='fecha_entrada',
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
