# Generated by Django 2.1.4 on 2018-12-24 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appStock', '0006_auto_20181223_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, editable=False)),
                ('cliente_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appStock.Cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appStock.Producto')),
            ],
            options={
                'verbose_name_plural': 'Stock en Clientes',
            },
        ),
    ]
